name: Test CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python main.py